services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Authentication\:
        resource: '../tests/Authentication/*'

    Tests\Authentication\Unit\Infrastructure\Symfony\Adapter\GoogleClientAdapterStub:
        public: true
        
    Authentication\Infrastructure\Symfony\Adapter\GoogleAuthenticationAdapter:
        arguments:
            $googleClient: '@Tests\Authentication\Unit\Infrastructure\Symfony\Adapter\GoogleClientAdapterStub'
