# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name    
    Shared\:
        resource: '../src/Shared'
        exclude:
            - '../src/Shared/Infrastructure/Symfony/Kernel.php'

    Shared\Infrastructure\Symfony\Controller\:
        resource: '../src/Shared/Infrastructure/Symfony/Controller/'
        tags: [ 'controller.service_arguments' ]

    Authentication\:
        resource: '../src/Authentication'
        exclude:
            - '../src/Authentication/Domain/Entity/'

    Authentication\Infrastructure\Symfony\Controller\:
        resource: '../src/Authentication/Infrastructure/Symfony/Controller/'
        tags: [ 'controller.service_arguments' ]
    
    Authentication\Infrastructure\Symfony\Adapter\GoogleAuthenticationAdapter:
        arguments:
            $googleClient: '@Authentication\Infrastructure\Symfony\Adapter\GoogleClientAdapter'
    
    Authentication\Infrastructure\Symfony\Adapter\GoogleClientAdapter:
        decorates: 'knpu.oauth2.client.google'
        
    Authentication\Infrastructure\Symfony\Security\GoogleAuthenticator:
        arguments:
            $client: '@Authentication\Infrastructure\Symfony\Adapter\GoogleClientAdapter'
